## BUCLES
#condicion=0
#while condicion<11:
    #print(condicion)
    #condicion=condicion+1

#1
#condicion=1
#while condicion<21:
    #if condicion %2 == 0:
        #print(condicion)
    #condicion=condicion+1
  
  
#2
#condicion=2
#while condicion<21:
    #if condicion %2 == 0:
        #print(condicion)
    #condicion=condicion+2
 #b  pedir al usuario  la eda si ingresa  22 corte  sino sigue
 
 

#nombre= " "
#while nombre !='si':
    #nombre=input('ingrese su nombre: ')
    
#while True:
  #  nombre=input('como te llamas: ')
   # if nombre== 'si':
    #    break
              
while True:
    ganador =input('Ingresa el numero ganador: ')
    if ganador == '10':
        break
       